modLoader="javafml"
loaderVersion="[40,)"
license="All rights reserved"
[[mods]]
    modId="pamhc2crops"
    version="${file.jarVersion}"
    displayName="Pam's HarvestCraft 2 Crops"
    description='''
    Pam's HarvestCraft 2 Crops adds all new crops to the game
    '''

[[dependencies.pamhc2crops]]
    modId="forge"
    mandatory=true
    versionRange="[40,)"
    ordering="NONE"
    side="BOTH"

[[dependencies.pamhc2crops]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.18.2,)"
    ordering="NONE"
    side="BOTH"